language: ruby
cache: bundler

rvm:
  - jruby
  - 2.2.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - dominic.breuker@email.com
    on_failure: change
    on_success: never